name: Backup current repository to S3

on:
#   push:
#     branches:
#         - main

  schedule:
    - cron: "*/10 * * * *"   ## UTC time
#   workflow_dispatch:
    

permissions:
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: Install Git LFS
        run: git lfs install

      - name: Create mirror backup
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    ## Default github token
        run: |
          set -euo pipefail

          REPO_NAME="${GITHUB_REPOSITORY##*/}"    ## collect repo  name with owner name
          DATE_UTC="$(date -u +%F)"
          TS_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
          WORKDIR="$RUNNER_TEMP/repo-backup"
          mkdir -p "$WORKDIR"

          cd "$WORKDIR"

          echo "Cloning mirror of ${GITHUB_REPOSITORY}"
          git clone --mirror "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "${REPO_NAME}.git"

          # Best effort for Git LFS
          git -C "${REPO_NAME}.git" lfs fetch --all || true

          ARCHIVE_NAME="${REPO_NAME}-${TS_UTC}.git.tar.gz"
          tar -czf "$ARCHIVE_NAME" "${REPO_NAME}.git"

          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> "$GITHUB_ENV"
          echo "DATE_UTC=$DATE_UTC" >> "$GITHUB_ENV"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"

      - name: Upload archive to S3
        run: |
          aws s3 cp \
            "$RUNNER_TEMP/repo-backup/${ARCHIVE_NAME}" \
            "s3://${S3_BUCKET}/github-backups/${GITHUB_REPOSITORY}/${DATE_UTC}/${ARCHIVE_NAME}"

            